import React, { useState } from 'react';
import type { CounterfactualResponse, SimulationScenario } from '../types';

interface ExportDialogProps {
  isOpen: boolean;
  onClose: () => void;
  data: {
    stationId?: string;
    interventions?: Record<string, number>;
    result?: CounterfactualResponse;
    scenario?: SimulationScenario;
    analysisType?: string;
  };
}

/**
 * Export functionality for analysis results
 * Supports PDF and Excel export formats
 * **Validates: Requirements 15.6**
 */
export const ExportDialog: React.FC<ExportDialogProps> = ({ isOpen, onClose, data }) => {
  const [exportFormat, setExportFormat] = useState<'pdf' | 'excel'>('pdf');
  const [includeCharts, setIncludeCharts] = useState(true);
  const [includeRawData, setIncludeRawData] = useState(false);
  const [exporting, setExporting] = useState(false);

  if (!isOpen) return null;

  const handleExport = async () => {
    setExporting(true);

    try {
      if (exportFormat === 'pdf') {
        await exportToPDF();
      } else {
        await exportToExcel();
      }
    } catch (error) {
      console.error('Export failed:', error);
      alert('Export failed. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  const exportToPDF = async () => {
    // Generate PDF content
    const content = generateExportContent();

    // Create a simple HTML document for PDF generation
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Causal Analysis Report</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
          h1 { color: #007bff; border-bottom: 3px solid #007bff; padding-bottom: 10px; }
          h2 { color: #333; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
          .section { margin: 20px 0; }
          .metric { display: inline-block; margin: 10px 20px 10px 0; padding: 15px; background: #f8f9fa; border-radius: 4px; }
          .metric-label { font-size: 12px; color: #666; }
          .metric-value { font-size: 24px; font-weight: bold; color: #007bff; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
          th { background-color: #007bff; color: white; }
          .positive { color: #28a745; }
          .negative { color: #dc3545; }
          .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">
          <p>Generated by Causal AI Manufacturing Platform on ${new Date().toLocaleString()}</p>
          <p>Station: ${data.stationId || 'N/A'}</p>
        </div>
      </body>
      </html>
    `;

    // Create a blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `causal-analysis-${data.stationId || 'report'}-${Date.now()}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    // Note: For true PDF generation, you would integrate with a library like jsPDF or pdfmake
    // or send the data to a backend service that generates PDFs
    alert(
      'Report exported as HTML. For PDF format, please print this file to PDF from your browser.'
    );
  };

  const exportToExcel = async () => {
    // Generate CSV content (Excel-compatible)
    const csvContent = generateCSVContent();

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `causal-analysis-${data.stationId || 'data'}-${Date.now()}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const generateExportContent = (): string => {
    let content = `
      <h1>Causal Analysis Report</h1>
      <div class="section">
        <p><strong>Analysis Type:</strong> ${data.analysisType || 'Counterfactual Simulation'}</p>
        <p><strong>Station ID:</strong> ${data.stationId || 'N/A'}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      </div>
    `;

    if (data.interventions && Object.keys(data.interventions).length > 0) {
      content += `
        <h2>Interventions</h2>
        <div class="section">
          <p>The following variables were modified:</p>
          <table>
            <thead>
              <tr>
                <th>Variable</th>
                <th>Intervention Value</th>
              </tr>
            </thead>
            <tbody>
              ${Object.entries(data.interventions)
                .map(
                  ([variable, value]) => `
                <tr>
                  <td>${variable}</td>
                  <td>${typeof value === 'number' ? value.toFixed(2) : value}</td>
                </tr>
              `
                )
                .join('')}
            </tbody>
          </table>
        </div>
      `;
    }

    if (data.result) {
      content += `
        <h2>Results</h2>
        <div class="section">
          <h3>Factual Outcomes (Current State)</h3>
          <table>
            <thead>
              <tr>
                <th>Variable</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              ${Object.entries(data.result.factual)
                .map(
                  ([variable, value]) => `
                <tr>
                  <td>${variable}</td>
                  <td>${typeof value === 'number' ? value.toFixed(2) : value}</td>
                </tr>
              `
                )
                .join('')}
            </tbody>
          </table>

          <h3>Counterfactual Outcomes (Predicted State)</h3>
          <table>
            <thead>
              <tr>
                <th>Variable</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              ${Object.entries(data.result.counterfactual)
                .map(
                  ([variable, value]) => `
                <tr>
                  <td>${variable}</td>
                  <td>${typeof value === 'number' ? value.toFixed(2) : value}</td>
                </tr>
              `
                )
                .join('')}
            </tbody>
          </table>

          <h3>Impact Analysis</h3>
          <table>
            <thead>
              <tr>
                <th>Variable</th>
                <th>Change</th>
                <th>Confidence Interval</th>
              </tr>
            </thead>
            <tbody>
              ${Object.entries(data.result.difference)
                .map(([variable, diff]) => {
                  const ci = data.result?.confidence_intervals[variable];
                  const diffValue = typeof diff === 'number' ? diff : 0;
                  const className = diffValue >= 0 ? 'positive' : 'negative';
                  return `
                    <tr>
                      <td>${variable}</td>
                      <td class="${className}">${diffValue >= 0 ? '+' : ''}${diffValue.toFixed(2)}</td>
                      <td>${ci ? `[${ci[0].toFixed(2)}, ${ci[1].toFixed(2)}]` : 'N/A'}</td>
                    </tr>
                  `;
                })
                .join('')}
            </tbody>
          </table>
        </div>
      `;
    }

    return content;
  };

  const generateCSVContent = (): string => {
    let csv = 'Causal Analysis Export\n';
    csv += `Generated,${new Date().toISOString()}\n`;
    csv += `Station,${data.stationId || 'N/A'}\n`;
    csv += `Analysis Type,${data.analysisType || 'Counterfactual Simulation'}\n\n`;

    if (data.interventions && Object.keys(data.interventions).length > 0) {
      csv += 'Interventions\n';
      csv += 'Variable,Value\n';
      Object.entries(data.interventions).forEach(([variable, value]) => {
        csv += `${variable},${value}\n`;
      });
      csv += '\n';
    }

    if (data.result) {
      csv += 'Results\n';
      csv += 'Variable,Factual,Counterfactual,Difference,CI Lower,CI Upper\n';
      Object.keys(data.result.factual).forEach((variable) => {
        const factual = data.result!.factual[variable];
        const counterfactual = data.result!.counterfactual[variable];
        const difference = data.result!.difference[variable];
        const ci = data.result!.confidence_intervals[variable];
        csv += `${variable},${factual},${counterfactual},${difference},${ci ? ci[0] : ''},${ci ? ci[1] : ''}\n`;
      });
    }

    return csv;
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
      }}
      onClick={onClose}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          backgroundColor: 'white',
          borderRadius: '8px',
          padding: '30px',
          maxWidth: '500px',
          width: '90%',
          boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
        }}
      >
        <h2 style={{ margin: '0 0 20px 0' }}>Export Analysis Results</h2>

        {/* Format Selection */}
        <div style={{ marginBottom: '25px' }}>
          <label style={{ display: 'block', marginBottom: '10px', fontWeight: 'bold' }}>
            Export Format:
          </label>
          <div style={{ display: 'flex', gap: '15px' }}>
            <label
              style={{
                flex: 1,
                padding: '15px',
                border: `2px solid ${exportFormat === 'pdf' ? '#007bff' : '#ddd'}`,
                borderRadius: '8px',
                cursor: 'pointer',
                textAlign: 'center',
                backgroundColor: exportFormat === 'pdf' ? '#e7f3ff' : 'white',
                transition: 'all 0.2s',
              }}
            >
              <input
                type="radio"
                name="format"
                value="pdf"
                checked={exportFormat === 'pdf'}
                onChange={() => setExportFormat('pdf')}
                style={{ marginRight: '8px' }}
              />
              <span style={{ fontSize: '24px', display: 'block', marginBottom: '5px' }}>📄</span>
              <strong>PDF Report</strong>
              <p style={{ fontSize: '12px', color: '#666', margin: '5px 0 0 0' }}>
                Formatted document with charts
              </p>
            </label>

            <label
              style={{
                flex: 1,
                padding: '15px',
                border: `2px solid ${exportFormat === 'excel' ? '#007bff' : '#ddd'}`,
                borderRadius: '8px',
                cursor: 'pointer',
                textAlign: 'center',
                backgroundColor: exportFormat === 'excel' ? '#e7f3ff' : 'white',
                transition: 'all 0.2s',
              }}
            >
              <input
                type="radio"
                name="format"
                value="excel"
                checked={exportFormat === 'excel'}
                onChange={() => setExportFormat('excel')}
                style={{ marginRight: '8px' }}
              />
              <span style={{ fontSize: '24px', display: 'block', marginBottom: '5px' }}>📊</span>
              <strong>Excel/CSV</strong>
              <p style={{ fontSize: '12px', color: '#666', margin: '5px 0 0 0' }}>
                Raw data for analysis
              </p>
            </label>
          </div>
        </div>

        {/* Export Options */}
        {exportFormat === 'pdf' && (
          <div style={{ marginBottom: '25px' }}>
            <label style={{ display: 'block', marginBottom: '10px', fontWeight: 'bold' }}>
              Include in Report:
            </label>
            <label
              style={{
                display: 'flex',
                alignItems: 'center',
                padding: '10px',
                cursor: 'pointer',
                borderRadius: '4px',
              }}
              onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#f8f9fa')}
              onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = 'transparent')}
            >
              <input
                type="checkbox"
                checked={includeCharts}
                onChange={(e) => setIncludeCharts(e.target.checked)}
                style={{ marginRight: '10px', width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span>Include charts and visualizations</span>
            </label>
            <label
              style={{
                display: 'flex',
                alignItems: 'center',
                padding: '10px',
                cursor: 'pointer',
                borderRadius: '4px',
              }}
              onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#f8f9fa')}
              onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = 'transparent')}
            >
              <input
                type="checkbox"
                checked={includeRawData}
                onChange={(e) => setIncludeRawData(e.target.checked)}
                style={{ marginRight: '10px', width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span>Include raw data tables</span>
            </label>
          </div>
        )}

        {/* Natural Language Summary */}
        <div
          style={{
            padding: '15px',
            backgroundColor: '#e7f3ff',
            border: '1px solid #b3d9ff',
            borderRadius: '4px',
            marginBottom: '25px',
          }}
        >
          <strong style={{ display: 'block', marginBottom: '5px' }}>What will be exported:</strong>
          <p style={{ margin: 0, fontSize: '14px' }}>
            {exportFormat === 'pdf'
              ? 'A formatted report with your analysis results, interventions, and predicted outcomes.'
              : 'A spreadsheet with all data in tabular format, ready for further analysis in Excel or other tools.'}
          </p>
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
          <button
            onClick={onClose}
            disabled={exporting}
            style={{
              padding: '10px 20px',
              backgroundColor: '#6c757d',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              cursor: exporting ? 'not-allowed' : 'pointer',
              fontSize: '16px',
            }}
          >
            Cancel
          </button>
          <button
            onClick={handleExport}
            disabled={exporting}
            style={{
              padding: '10px 20px',
              backgroundColor: exporting ? '#ccc' : '#007bff',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              cursor: exporting ? 'not-allowed' : 'pointer',
              fontSize: '16px',
              fontWeight: 'bold',
            }}
          >
            {exporting ? 'Exporting...' : `Export as ${exportFormat.toUpperCase()}`}
          </button>
        </div>
      </div>
    </div>
  );
};
